// pub mod minimal;
pub mod auto_operations; // These fail now for some reason, fix
pub mod auto_transitions;
pub mod disabled;
pub mod failed_fatal;
pub mod failed_retries;
pub mod failed_bypass;
pub mod replan;
pub mod state;
pub mod timeout_bypass;
pub mod timeout_disabled;
pub mod timeout_fatal;
pub mod timeout_retries;
pub mod emergency;
pub mod sop_sequence;
pub mod sop_parallel;
pub mod sop_alternative;
pub mod scheduled_goals;
pub mod incoming_goals;
pub mod counter_goal;