// pub mod minimal;
pub mod auto_operations;
pub mod auto_transitions;
pub mod disabled;
pub mod failed_fatal;
pub mod failed_retries;
pub mod failed_bypass;
pub mod replan;
pub mod state;
pub mod timeout_bypass;
pub mod timeout_disabled;
pub mod timeout_fatal;
pub mod timeout_retries;
pub mod emergency;
pub mod sop_sequence;
pub mod sop_parallel;
pub mod sop_alternative;